version: '3.5'
name: pixuleco-development
services:
  redis:
   image: redis:latest
   ports:
    - "6379:6379"
   volumes:
    - redis-volume:/data

  db:
    image: postgres:17.5
    container_name: pixuleco-development-database
    ports:
      - "5432:5432"
    restart: always
    volumes: 
     - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pixuleco-development-database

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '8080:8080'
    depends_on:
      - db

  api:
    container_name: pixuleco-development
    build: .
    volumes:
      - ./src:/app/src
    ports:
     - "3000:3000"
    restart: always
    environment:
      - PORT=${PORT}
    depends_on:
      db:
       condition: service_healthy
      redis:
       condition: service_healthy

volumes: 
  redis-volume: {}
  database-data: {}
